export const INCREASE_SEARCH = "INCREMENT_SEARCH"
export const DECREASE_SEARCH = "DECREASE_SEARCH" 
export const SELECTED_CHAR = "SELECTED_CHAR"
export const SELECTED_SINGLE_CHAR = "SELECTED_SINGLE_CHAR"