export const INCREASE_SEARCH = "INCREMENT_SEARCH"
export const DECREASE_SEARCH = "DECREASE_SEARCH" 
export const SELECTED_CHAR = "SELECTED_CHAR"
export const PAGE_LOADING = 'PAGE_LOADING'
export const GET_MORE_PAGINATION = "GET_MORE_PAGINATION"